# This file is a part of globus-registered-api.
# https://github.com/globus/globus-registered-api
# Copyright 2025-2026 Globus <support@globus.org>
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import json
import typing as t
from datetime import datetime
from pathlib import Path

import click
import openapi_pydantic as oa
from pydantic import BaseModel
from pydantic import field_serializer
from pydantic import field_validator

from globus_registered_api.openapi.reducer import OpenAPITarget

_MANIFEST_PATH = Path(".globus_registered_api/manifest.json")

_MANIFEST_COMMENT = [
    "===========================================================",
    "⚠️  WARNING: AUTO-GENERATED FILE — DO NOT MODIFY DIRECTLY  ⚠️",
    "===========================================================",
    "This file was automatically generated by the globus-registered-api cli.",
    "Any manual changes made to this file will be overwritten.",
    "",
    "To make changes, configure the repository using `globus-registered-api manage`.",
    "Then re-generate using `globus-registered-api build`.",
    "===========================================================",
]


class ComputedRegisteredAPI(BaseModel):
    """Represents a single registered API target with its enriched specification."""

    target: OpenAPITarget
    description: str

    @field_validator("target", mode="before")
    @classmethod
    def ensure_target(cls, value: dict[str, t.Any] | OpenAPITarget) -> OpenAPITarget:
        """Validate and convert target field to OpenAPITarget."""
        if isinstance(value, OpenAPITarget):
            return value
        elif isinstance(value, dict):
            return OpenAPITarget(
                operation=oa.Operation.model_validate(value["specification"]),
                destination=value["destination"],
                components=value.get("components"),
                transforms=value.get("transforms"),
            )

        raise ValueError(f"Unrecognized target type: {type(value)}")

    @field_serializer("target")
    def serialize_target(self, value: OpenAPITarget) -> dict[str, t.Any]:
        return value.to_dict()


class RegisteredAPIManifest(BaseModel):
    """
    Manifest file modeling all registered APIs in the repository.
    """

    build_timestamp: datetime
    registered_apis: dict[str, ComputedRegisteredAPI]

    def commit(self) -> None:
        """Write the manifest to disk at .globus_registered_api/manifest.json."""
        _MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

        # Build the full manifest dict with comment header
        manifest_dict = {
            "_comment": _MANIFEST_COMMENT,
            "build_timestamp": self.build_timestamp.isoformat(),
            "registered-apis": {
                alias: api.model_dump() for alias, api in self.registered_apis.items()
            },
        }

        # Write with explicit formatting to ensure:
        # - 4-space indentation (matches config.json)
        # - Alphabetically sorted keys (for git diff)
        # - Unicode characters preserved (emojis, em-dash)
        with _MANIFEST_PATH.open("w", encoding="utf-8") as f:
            json.dump(manifest_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
            f.write("\n")

    @classmethod
    def load(cls) -> RegisteredAPIManifest:
        """Load the manifest from disk."""
        if not cls.exists():
            click.echo("Error: Missing repository manifest file.")
            click.echo("Run 'gra build' first to generate a manifest.")
            raise click.Abort()

        manifest_data = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))

        # Extract the fields we care about (ignore _comment)
        return cls(
            build_timestamp=datetime.fromisoformat(manifest_data["build_timestamp"]),
            registered_apis={
                alias: ComputedRegisteredAPI(**api_data)
                for alias, api_data in manifest_data["registered-apis"].items()
            },
        )

    @classmethod
    def exists(cls) -> bool:
        """Check if a manifest file exists on disk."""
        return _MANIFEST_PATH.is_file()
