# This file is a part of globus-registered-api.
# https://github.com/globus/globus-registered-api
# Copyright 2025-2026 Globus <support@globus.org>
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import json
import typing as t
from datetime import datetime
from pathlib import Path

import click
import openapi_pydantic as oa
from pydantic import BaseModel
from pydantic import Field
from pydantic import PlainSerializer
from pydantic import field_serializer
from pydantic import field_validator

from globus_registered_api.errors import GRACommandLineError
from globus_registered_api.openapi.reducer import OpenAPITarget

_MANIFEST_PATH = Path(".globus_registered_api/manifest.json")

_MANIFEST_COMMENT = [
    "===========================================================",
    "⚠️  WARNING: AUTO-GENERATED FILE — DO NOT MODIFY DIRECTLY  ⚠️",
    "===========================================================",
    "This file was automatically generated by the globus-registered-api cli.",
    "Any manual changes made to this file will be overwritten.",
    "",
    "To make changes, configure the repository using `globus-registered-api manage`.",
    "Then re-generate using `globus-registered-api build`.",
    "===========================================================",
]


_CURRENT_VERSION = "1.0"


class GRAManifest(BaseModel):
    """
    Manifest file modeling all registered APIs in the repository.
    """

    document_version: str = Field(default=_CURRENT_VERSION)

    build_timestamp: datetime
    registered_apis: dict[str, dict[str, ComputedRegisteredAPI]]

    @field_serializer("build_timestamp", mode="plain")
    def serialize_timestamp(self, value: datetime) -> str:
        return value.isoformat()

    @field_validator("document_version", mode="before")
    def validate_document_version(cls, v: t.Any) -> t.Any:
        if isinstance(v, str) and v != _CURRENT_VERSION:
            version_data = f"Version: {v}; Expected: {_CURRENT_VERSION}."
            raise GRACommandLineError(
                f"Out-of-date manifest document. {version_data}",
                "Run `gra build` to regenerate a new manifest.",
            )
        return v

    def commit(self) -> None:
        """Write the manifest to disk at .globus_registered_api/manifest.json."""
        _MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

        # Build the full manifest dict with comment header
        manifest_dict = {
            "_comment": _MANIFEST_COMMENT,
            **self.model_dump(),
        }

        # Write with explicit formatting to ensure:
        # - 4-space indentation (matches config.json)
        # - Alphabetically sorted keys (for git diff)
        # - Unicode characters preserved (emojis, em-dash)
        with _MANIFEST_PATH.open("w", encoding="utf-8") as f:
            json.dump(manifest_dict, f, indent=4, sort_keys=True, ensure_ascii=False)
            f.write("\n")

    @classmethod
    def load(cls) -> GRAManifest:
        """Load the manifest from disk."""
        if not _MANIFEST_PATH.is_file():
            raise GRACommandLineError(
                "Missing repository manifest file.",
                "Run 'gra build' first to generate a manifest.",
            )

        manifest_data = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
        if "_comment" in manifest_data:
            del manifest_data["_comment"]
        return cls.model_validate(manifest_data)

    @classmethod
    def path(cls) -> Path:
        return _MANIFEST_PATH


class ComputedRegisteredAPI(BaseModel):
    """Represents a single registered API target with its enriched specification."""

    target: OpenAPITarget
    description: str

    @field_validator("target", mode="before")
    @classmethod
    def ensure_target(cls, value: dict[str, t.Any] | OpenAPITarget) -> OpenAPITarget:
        """Validate and convert target field to OpenAPITarget."""
        if isinstance(value, OpenAPITarget):
            return value
        elif isinstance(value, dict):
            return OpenAPITarget(
                operation=oa.Operation.model_validate(value["specification"]),
                destination=value["destination"],
                components=value.get("components"),
            )

        raise ValueError(f"Unrecognized target type: {type(value)}")

    @field_serializer("target")
    def serialize_target(self, value: OpenAPITarget) -> dict[str, t.Any]:
        return value.to_dict()
